### Site Settings ###
url                 : "www.redouaneachouri.com"
title               : Redouane Achouri
description         : >-
                      "Curious about engineering and tech,
                      I build projects based on my inspirations
                      and needs around #webapps #devops
                      #dataengineering #datascience #iot."
baseurl             : ""
repository          : redouane-dev/redouane-dev.github.io
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


### Navbar Settings ###
nav_exclude:
  - pages/index.md
  - pages/tags.html
  - pages/404.html


### Author Info ###
author:
  name              : Redouane Achouri
  image             : ./assets/images/profile.jpg
  email             : redouane.a.achouri@gmail.com
  github            : redouane-dev
  linkedin          : redouane-achouri
  medium            : redouane.achouri


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Analytics ###
analytics:
  enabled: true
  google:
    tracking_id: G-Q3LBNQD0DY


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "Gemfile*"
  - "*.log"